
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization or
# the specific domain of the project.
name: 'dbt_cloud_bigquery_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# This MUST match the profile name in your ~/.dbt/profiles.yml file.
profile: 'dbt_cloud_bigquery_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ['models']
test-paths: ["tests"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets: These directories are removed when you run `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# This is where you configure how your models are materialized (table, view, incremental).
# The hierarchy follows your folder structure inside the 'models/' directory.
models:
  my_dbt_project:
    
    # Config for models found in models/staging/
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # Config for models found in models/marts/ (or 'core', 'serving')
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      
      # You can nest further if you have sub-folders like models/marts/finance/
      # finance:
        # +tags: ["finance"]

# Variables (Vars)
# You can define global variables here that can be referenced in your models 
# using {{ var('my_variable') }}.
vars:
  # Example: Define a start date for processing data
  start_date: '2023-01-01'
  
  # Example: Platform-specific flags
  my_dbt_project:
    is_production: false
